# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/student/Desktop/ceng2010_lab_q2/ceng2010_lab_q2.cache/wt [current_project]
set_property parent.project_path C:/Users/student/Desktop/ceng2010_lab_q2/ceng2010_lab_q2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/student/Desktop/ceng2010_lab_q2/ceng2010_lab_q2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/student/Desktop/ceng2010_lab_q2/ceng2010_lab_q2.srcs/sources_1/new/q2.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/student/Desktop/ceng2010_lab_q2/ceng2010_lab_q2.srcs/constrs_1/imports/Downloads/basys3_lab01.xdc
set_property used_in_implementation false [get_files C:/Users/student/Desktop/ceng2010_lab_q2/ceng2010_lab_q2.srcs/constrs_1/imports/Downloads/basys3_lab01.xdc]


synth_design -top q2 -part xc7a35ticpg236-1L


write_checkpoint -force -noxdef q2.dcp

catch { report_utilization -file q2_utilization_synth.rpt -pb q2_utilization_synth.pb }
